use UNIVERlab4

select PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME
from PULPIT inner join FACULTY
on PULPIT.FACULTY = FACULTY.FACULTY inner join PROFESSION
on PROFESSION.FACULTY = FACULTY.FACULTY 
where PROFESSION.PROFESSION_NAME like '%технлогии%' or PROFESSION_NAME like '%технология%'
