use UNIVERlab4
select AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY
from AUDITORIUM
where AUDITORIUM.AUDITORIUM_CAPACITY in (select top(1) a2.AUDITORIUM_CAPACITY from AUDITORIUM a2
order by AUDITORIUM_CAPACITY desc)