USE UNIVERlab4

SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME
FROM PULPIT, FACULTY, PROFESSION
WHERE PULPIT.FACULTY = FACULTY.FACULTY AND PROFESSION.FACULTY = PULPIT.FACULTY
AND PROFESSION.PROFESSION_NAME
IN (SELECT PROFESSION_NAME FROM PROFESSION
				WHERE PROFESSION_NAME LIKE '%технология%' or PROFESSION_NAME LIKE '%технологии%')